### ISSUE TITLE
[Suggestion] Interaction Suggestions

### ISSUE THREAD

**Issue by Darkmega18** [NiceHairs26/Symbiosis#1]
If a blob moves over a dead body it eats it up removing it and becoming larger, potentially faster.

Blob will get items stuck in it if it moves over them/absorbs a player who drops items into it, but will leave them if it finds a boombox to get distracted by?

When little girl is around a person (even when not looked at) their flashlights and other tools on them are turned off/dispowered...

If a turret is activated and locking on but you move out of the way it might pick up the targets of other entities nearby. For example a chasing braken, spider or lootbug etc.

If player is holding a flashbang when being picked up by a giant, automatically trigger it as a last resort.

Allow lockpicker or keys to instead be used to lock doors?

**Comment by NiceHairs26** [comment]
noted for future potential plans
